name: Node.js Package

on:
    push:
        branches:
            - main

jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/
                  scope: "@AlmostReliable"
                  cache: "pnpm"
            - run: pnpm install
            - run: pnpm release
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}
